INTRUCTIONS

Below are detailed instructions to run that code assuming your project root contains:
- InTrade Grevity exercises.ipyn
- grav_data.csv
- a folder called WIOD 2016 with the WIOD Stata file inside that folder, for example WIOT2014_October16_ROW.dta



        project_root/
  
        │
  
        ├─ grav_data.csv
  
        ├─ your_script.ipynb
  
        └─ WIOD 2016/
  
           └─ WIOT2014_October16_ROW.dta

In [94]:
# Import lybraries
import intrade as it
import numpy as np
import pandas as pd

In [97]:
# Create gravity object with gravity variables

grav_data = pd.read_csv("grav_data.csv")
grav_data = grav_data.dropna()
grav_data.exporter.unique()

dir_in = ""
obj = it.load_WIOD(dir_in,  2014, "WIOD 2016")

df = it.aggregate(obj)["df"]

obj_grav = it.obj_Grav(it.aggregate(obj))
obj_grav = obj_grav.merge(grav_data, on=["exporter", "importer"], how= "left")

# Drop ROW, no gravity data 
obj_grav = obj_grav[(obj_grav["exporter"] != "ROW") & (obj_grav["importer"] != "ROW")]

Year: 2014
File: WIOD\WIOT2014_October16_ROW

 Num Countries 44.0
 Num sect 56
 Num components FD 5
Done!
Done!
Done!
Gravity Object Done!

In [100]:
# Denine parameters and estimations

# seleccion   = 1                                          # 3 different exercises: 1-increase, 2-asif, 3-inout
pais_ref    = "DEU"                                      # reference country
sigma       = 7                                          # sigma - elasticidad de sustitución
increase    = 15                                         # increase only for 1-increase

paises1 = ["AUT", "BEL","BGR","HRV","CYP","CZE","DNK","EST","FIN","FRA","DEU","GRC","IRL","HUN","ITA","LVA","LTU","LUX","MLT","POL","NLD","PRT","ROU","SVK","SVN","ESP","SWE"]
paises2 = ["USA"]
paises3 = ["GBR"]

# TRANSFORM VARIABLES
# LN de distancia
obj_grav['LN_DIST'] = np.log(obj_grav['DIST'])
variables = ["LN_DIST", "CNTG", "LANG","BRDR"]

# *********************
# ONLY GRAV ESTIMATES,
# *********************
(it.struc_grav(obj_grav,variables,pais_ref))

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                  trade   No. Observations:                 1849
Model:                            GLM   Df Residuals:                     1760
Model Family:                 Poisson   Df Model:                           88
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:            -3.1817e+06
Date:                Fri, 03 Apr 2026   Deviance:                   6.3473e+06
Time:                        15:46:21   Pearson chi2:                 7.44e+06
No. Iterations:                    11   Pseudo R-squ. (CS):              1.000
Covariance Type:                  HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
BRDR          -2.0534      0.592     -3.468      0.001      -3.214      -0.893
LN_DIST       -0.5962      0.043    -13.760      0.000      -0.681      -0.511
CNTG           0.6729      0.159      4.232      0.000       0.361       0.985
LANG           0.0754      0.138      0.544      0.586      -0.196       0.347
BRDR          -2.0534      0.271     -7.580      0.000      -2.584      -1.522
exp_fe_AUS    18.7101      0.342     54.668      0.000      18.039      19.381
exp_fe_AUT    17.3125      0.308     56.244      0.000      16.709      17.916
exp_fe_BEL    17.3417      0.287     60.394      0.000      16.779      17.905
exp_fe_BGR    16.1678      0.324     49.922      0.000      15.533      16.803
exp_fe_BRA    18.8150      0.320     58.733      0.000      18.187      19.443
exp_fe_CAN    18.5563      0.339     54.810      0.000      17.893      19.220
exp_fe_CHE    17.4879      0.276     63.373      0.000      16.947      18.029
exp_fe_CHN    20.1164      0.340     59.090      0.000      19.449      20.784
exp_fe_CYP    15.2045      0.322     47.290      0.000      14.574      15.835
exp_fe_CZE    17.0677      0.273     62.445      0.000      16.532      17.603
exp_fe_DEU    18.8265      0.251     74.963      0.000      18.334      19.319
exp_fe_DNK    17.0495      0.265     64.405      0.000      16.531      17.568
exp_fe_ESP    18.1726      0.298     60.909      0.000      17.588      18.757
exp_fe_EST    15.5574      0.340     45.798      0.000      14.892      16.223
exp_fe_FIN    17.2129      0.304     56.549      0.000      16.616      17.810
exp_fe_FRA    18.5012      0.284     65.122      0.000      17.944      19.058
exp_fe_GBR    18.3423      0.294     62.480      0.000      17.767      18.918
exp_fe_GRC    16.7925      0.306     54.824      0.000      16.192      17.393
exp_fe_HRV    15.9185      0.344     46.326      0.000      15.245      16.592
exp_fe_HUN    16.7533      0.338     49.594      0.000      16.091      17.415
exp_fe_IDN    18.2857      0.315     57.969      0.000      17.667      18.904
exp_fe_IND    18.7316      0.347     54.031      0.000      18.052      19.411
exp_fe_IRL    16.9726      0.412     41.231      0.000      16.166      17.779
exp_fe_ITA    18.4252      0.307     60.037      0.000      17.824      19.027
exp_fe_JPN    18.8520      0.317     59.525      0.000      18.231      19.473
exp_fe_KOR    18.4072      0.366     50.325      0.000      17.690      19.124
exp_fe_LTU    15.8427      0.323     49.095      0.000      15.210      16.475
exp_fe_LUX    15.6868      0.340     46.106      0.000      15.020      16.354
exp_fe_LVA    15.6916      0.387     40.496      0.000      14.932      16.451
exp_fe_MEX    18.2840      0.434     42.142      0.000      17.434      19.134
exp_fe_MLT    14.6532      0.371     39.544      0.000      13.927      15.379
exp_fe_NLD    17.7791      0.406     43.763      0.000      16.983      18.575
exp_fe_NOR    17.5587      0.303     57.995      0.000      16.965      18.152
exp_fe_POL    17.6829      0.289     61.225      0.000      17.117      18.249
exp_fe_PRT    16.8470      0.290     58.000      0.000      16.278      17.416
exp_fe_ROU    17.0255      0.302     56.294      0.000      16.433      17.618
exp_fe_RUS    18.7933      0.329     57.077      0.000      18.148      19.439
exp_fe_SVK    16.5224      0.298     55.496      0.000      15.939      17.106
exp_fe_SVN    15.8278      0.302     52.445      0.000      15.236      16.419
exp_fe_SWE    17.6485      0.291     60.637      0.000      17.078      18.219
exp_fe_TUR    17.8904      0.298     60.098      0.000      17.307      18.474
exp_fe_TWN    17.7301      0.413     42.924      0.000      16.920      18.540
exp_fe_USA    19.7198      0.327     60.240      0.000      19.078      20.361
imp_fe_AUS     0.1247      0.222      0.563      0.574      -0.310       0.559
imp_fe_AUT    -1.2497      0.228     -5.478      0.000      -1.697      -0.803
imp_fe_BEL    -1.2344      0.214     -5.772      0.000      -1.654      -0.815
imp_fe_BGR    -2.2022      0.231     -9.542      0.000      -2.655      -1.750
imp_fe_BRA     0.4865      0.191      2.550      0.011       0.113       0.860
imp_fe_CAN     0.3702      0.225      1.645      0.100      -0.071       0.811
imp_fe_CHE    -1.0461      0.188     -5.555      0.000      -1.415      -0.677
imp_fe_CHN     1.2867      0.212      6.083      0.000       0.872       1.701
imp_fe_CYP    -3.0552      0.233    -13.126      0.000      -3.511      -2.599
imp_fe_CZE    -1.5966      0.165     -9.663      0.000      -1.920      -1.273
imp_fe_DNK    -1.4796      0.170     -8.711      0.000      -1.812      -1.147
imp_fe_ESP    -0.2607      0.191     -1.363      0.173      -0.636       0.114
imp_fe_EST    -2.8844      0.264    -10.941      0.000      -3.401      -2.368
imp_fe_FIN    -1.2311      0.202     -6.103      0.000      -1.626      -0.836
imp_fe_FRA     0.1162      0.172      0.678      0.498      -0.220       0.452
imp_fe_GBR     0.1228      0.197      0.625      0.532      -0.262       0.508
imp_fe_GRC    -1.3722      0.204     -6.711      0.000      -1.773      -0.971
imp_fe_HRV    -2.4577      0.255     -9.622      0.000      -2.958      -1.957
imp_fe_HUN    -1.8531      0.250     -7.421      0.000      -2.343      -1.364
imp_fe_IDN    -0.3722      0.191     -1.953      0.051      -0.746       0.001
imp_fe_IND     0.1887      0.241      0.782      0.434      -0.284       0.662
imp_fe_IRL    -1.5853      0.385     -4.114      0.000      -2.341      -0.830
imp_fe_ITA    -0.1750      0.208     -0.840      0.401      -0.584       0.233
imp_fe_JPN     0.2835      0.217      1.309      0.191      -0.141       0.708
imp_fe_KOR    -0.6912      0.268     -2.580      0.010      -1.216      -0.166
imp_fe_LTU    -2.6214      0.233    -11.254      0.000      -3.078      -2.165
imp_fe_LUX    -2.2916      0.326     -7.040      0.000      -2.930      -1.654
imp_fe_LVA    -2.7032      0.306     -8.831      0.000      -3.303      -2.103
imp_fe_MEX    -0.1260      0.367     -0.344      0.731      -0.844       0.592
imp_fe_MLT    -3.7005      0.317    -11.674      0.000      -4.322      -3.079
imp_fe_NLD    -1.1287      0.353     -3.200      0.001      -1.820      -0.437
imp_fe_NOR    -1.0358      0.198     -5.240      0.000      -1.423      -0.648
imp_fe_POL    -0.8765      0.172     -5.082      0.000      -1.215      -0.538
imp_fe_PRT    -1.3909      0.201     -6.926      0.000      -1.785      -0.997
imp_fe_ROU    -1.3916      0.200     -6.959      0.000      -1.784      -1.000
imp_fe_RUS     0.3433      0.202      1.702      0.089      -0.052       0.739
imp_fe_SVK    -2.1036      0.219     -9.620      0.000      -2.532      -1.675
imp_fe_SVN    -2.6742      0.218    -12.293      0.000      -3.101      -2.248
imp_fe_SWE    -0.8158      0.179     -4.563      0.000      -1.166      -0.465
imp_fe_TUR    -0.4559      0.180     -2.527      0.012      -0.809      -0.102
imp_fe_TWN    -1.4318      0.338     -4.235      0.000      -2.094      -0.769
imp_fe_USA     1.6857      0.212      7.968      0.000       1.271       2.100
==============================================================================
"""

In [101]:
# Contrafactua increase in trade cost

(it.struc_grav_incre(obj_grav, variables, paises1, paises2, pais_ref , increase, sigma))

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                  trade   No. Observations:                 1849
Model:                            GLM   Df Residuals:                     1759
Model Family:                 Poisson   Df Model:                           89
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:            -3.1779e+06
Date:                Fri, 03 Apr 2026   Deviance:                   6.3397e+06
Time:                        15:46:26   Pearson chi2:                 7.40e+06
No. Iterations:                    10   Pseudo R-squ. (CS):              1.000
Covariance Type:                  HC3
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
LN_DIST       -0.5987      0.044    -13.733      0.000      -0.684      -0.513
CNTG           0.6777      0.159      4.256      0.000       0.366       0.990
LANG           0.0759      0.139      0.547      0.585      -0.196       0.348
BRDR          -4.1100      0.115    -35.859      0.000      -4.335      -3.885
BRDR_27USA    -4.0025      0.191    -20.982      0.000      -4.376      -3.629
exp_fe_AUS    18.7309      0.343     54.552      0.000      18.058      19.404
exp_fe_AUT    17.3256      0.309     56.125      0.000      16.721      17.931
exp_fe_BEL    17.3541      0.286     60.597      0.000      16.793      17.915
exp_fe_BGR    16.1812      0.325     49.728      0.000      15.543      16.819
exp_fe_BRA    18.8345      0.321     58.639      0.000      18.205      19.464
exp_fe_CAN    18.5783      0.340     54.611      0.000      17.912      19.245
exp_fe_CHE    17.5030      0.277     63.233      0.000      16.960      18.045
exp_fe_CHN    20.1376      0.342     58.863      0.000      19.467      20.808
exp_fe_CYP    15.2167      0.323     47.127      0.000      14.584      15.850
exp_fe_CZE    17.0807      0.275     62.168      0.000      16.542      17.619
exp_fe_DEU    18.8403      0.252     74.617      0.000      18.345      19.335
exp_fe_DNK    17.0622      0.266     64.202      0.000      16.541      17.583
exp_fe_ESP    18.1865      0.301     60.513      0.000      17.597      18.776
exp_fe_EST    15.5703      0.341     45.644      0.000      14.902      16.239
exp_fe_FIN    17.2270      0.306     56.370      0.000      16.628      17.826
exp_fe_FRA    18.5155      0.285     65.025      0.000      17.957      19.074
exp_fe_GBR    18.3576      0.294     62.375      0.000      17.781      18.934
exp_fe_GRC    16.8061      0.308     54.594      0.000      16.203      17.409
exp_fe_HRV    15.9315      0.345     46.208      0.000      15.256      16.607
exp_fe_HUN    16.7665      0.339     49.474      0.000      16.102      17.431
exp_fe_IDN    18.3057      0.316     57.838      0.000      17.685      18.926
exp_fe_IND    18.7513      0.348     53.934      0.000      18.070      19.433
exp_fe_IRL    16.9848      0.403     42.111      0.000      16.194      17.775
exp_fe_ITA    18.4390      0.308     59.902      0.000      17.836      19.042
exp_fe_JPN    18.8704      0.318     59.315      0.000      18.247      19.494
exp_fe_KOR    18.4272      0.369     49.994      0.000      17.705      19.150
exp_fe_LTU    15.8558      0.324     48.964      0.000      15.221      16.490
exp_fe_LUX    15.6977      0.339     46.285      0.000      15.033      16.362
exp_fe_LVA    15.7047      0.389     40.391      0.000      14.943      16.467
exp_fe_MEX    18.3045      0.437     41.934      0.000      17.449      19.160
exp_fe_MLT    14.6630      0.372     39.377      0.000      13.933      15.393
exp_fe_NLD    17.7917      0.405     43.930      0.000      16.998      18.585
exp_fe_NOR    17.5763      0.304     57.906      0.000      16.981      18.171
exp_fe_POL    17.6969      0.290     60.921      0.000      17.128      18.266
exp_fe_PRT    16.8598      0.293     57.601      0.000      16.286      17.434
exp_fe_ROU    17.0394      0.304     56.022      0.000      16.443      17.636
exp_fe_RUS    18.8131      0.330     56.965      0.000      18.166      19.460
exp_fe_SVK    16.5351      0.299     55.264      0.000      15.949      17.122
exp_fe_SVN    15.8402      0.303     52.262      0.000      15.246      16.434
exp_fe_SWE    17.6626      0.292     60.404      0.000      17.090      18.236
exp_fe_TUR    17.9076      0.298     59.992      0.000      17.323      18.493
exp_fe_TWN    17.7499      0.416     42.642      0.000      16.934      18.566
exp_fe_USA    19.7441      0.331     59.688      0.000      19.096      20.392
imp_fe_AUS     0.1229      0.221      0.556      0.578      -0.310       0.556
imp_fe_AUT    -1.2510      0.228     -5.494      0.000      -1.697      -0.805
imp_fe_BEL    -1.2361      0.212     -5.824      0.000      -1.652      -0.820
imp_fe_BGR    -2.2034      0.231     -9.549      0.000      -2.656      -1.751
imp_fe_BRA     0.4860      0.189      2.572      0.010       0.116       0.856
imp_fe_CAN     0.3669      0.224      1.638      0.101      -0.072       0.806
imp_fe_CHE    -1.0486      0.188     -5.580      0.000      -1.417      -0.680
imp_fe_CHN     1.2841      0.212      6.071      0.000       0.870       1.699
imp_fe_CYP    -3.0575      0.233    -13.122      0.000      -3.514      -2.601
imp_fe_CZE    -1.5978      0.165     -9.684      0.000      -1.921      -1.274
imp_fe_DNK    -1.4811      0.169     -8.748      0.000      -1.813      -1.149
imp_fe_ESP    -0.2607      0.192     -1.359      0.174      -0.637       0.115
imp_fe_EST    -2.8864      0.264    -10.943      0.000      -3.403      -2.369
imp_fe_FIN    -1.2320      0.201     -6.121      0.000      -1.627      -0.838
imp_fe_FRA     0.1161      0.170      0.682      0.495      -0.218       0.450
imp_fe_GBR     0.1219      0.196      0.621      0.535      -0.263       0.507
imp_fe_GRC    -1.3733      0.204     -6.717      0.000      -1.774      -0.973
imp_fe_HRV    -2.4589      0.255     -9.634      0.000      -2.959      -1.959
imp_fe_HUN    -1.8542      0.250     -7.430      0.000      -2.343      -1.365
imp_fe_IDN    -0.3748      0.189     -1.980      0.048      -0.746      -0.004
imp_fe_IND     0.1867      0.241      0.776      0.438      -0.285       0.658
imp_fe_IRL    -1.5866      0.379     -4.191      0.000      -2.329      -0.845
imp_fe_ITA    -0.1753      0.208     -0.843      0.399      -0.583       0.232
imp_fe_JPN     0.2797      0.217      1.288      0.198      -0.146       0.705
imp_fe_KOR    -0.6981      0.270     -2.588      0.010      -1.227      -0.169
imp_fe_LTU    -2.6231      0.233    -11.269      0.000      -3.079      -2.167
imp_fe_LUX    -2.2945      0.323     -7.096      0.000      -2.928      -1.661
imp_fe_LVA    -2.7050      0.306     -8.835      0.000      -3.305      -2.105
imp_fe_MEX    -0.1292      0.369     -0.350      0.726      -0.852       0.594
imp_fe_MLT    -3.7044      0.318    -11.647      0.000      -4.328      -3.081
imp_fe_NLD    -1.1301      0.352     -3.215      0.001      -1.819      -0.441
imp_fe_NOR    -1.0373      0.196     -5.281      0.000      -1.422      -0.652
imp_fe_POL    -0.8771      0.172     -5.089      0.000      -1.215      -0.539
imp_fe_PRT    -1.3923      0.202     -6.899      0.000      -1.788      -0.997
imp_fe_ROU    -1.3922      0.200     -6.957      0.000      -1.784      -1.000
imp_fe_RUS     0.3438      0.201      1.714      0.087      -0.049       0.737
imp_fe_SVK    -2.1051      0.219     -9.626      0.000      -2.534      -1.676
imp_fe_SVN    -2.6760      0.217    -12.314      0.000      -3.102      -2.250
imp_fe_SWE    -0.8162      0.178     -4.581      0.000      -1.165      -0.467
imp_fe_TUR    -0.4564      0.179     -2.549      0.011      -0.807      -0.106
imp_fe_TWN    -1.4394      0.341     -4.226      0.000      -2.107      -0.772
imp_fe_USA     1.6786      0.208      8.053      0.000       1.270       2.087
==============================================================================
trade        1.302876e+08
trade_BLN    1.302876e+08
dtype: float64
['USA'] increase trade cost with ['AUT', 'BEL', 'BGR', 'HRV', 'CYP', 'CZE', 'DNK', 'EST', 'FIN', 'FRA', 'DEU', 'GRC', 'IRL', 'HUN', 'ITA', 'LVA', 'LTU', 'LUX', 'MLT', 'POL', 'NLD', 'PRT', 'ROU', 'SVK', 'SVN', 'ESP', 'SWE'] in  15%
8.403731044381857e-10
0.002444464753352804 1.992157194763422e-08 0.0
   País    Export%  Renta_Real%   Output%  P_Consumo%
0   AUS  -0.238722     0.003905 -0.513390   -0.517274
1   AUT  -3.080707    -0.127617 -0.895741   -0.769105
2   BEL  -3.102621    -0.105718 -0.887013   -0.782122
3   BGR  -3.552989    -0.318708 -0.900743   -0.583896
4   BRA  -0.150488     0.005012 -0.496541   -0.501528
5   CAN   0.247300     0.021532 -0.190881   -0.212367
6   CHE  -0.395563     0.010677 -0.688738   -0.699340
7   CHN  -0.267996     0.001090 -0.547446   -0.548529
8   CYP  -4.677608    -0.363714 -0.884645   -0.522832
9   CZE  -3.012601    -0.167797 -0.943000   -0.776506
10  DEU  -3.137058    -0.058772 -0.929657   -0.871398
11  DNK  -3.838220    -0.148373 -0.902827   -0.755576
12  ESP  -5.452268    -0.110479 -0.847912   -0.738248
13  EST  -3.203936    -0.435010 -0.971268   -0.538601
14  FIN  -3.900884    -0.206141 -0.861618   -0.656831
15  FRA  -4.129529    -0.076432 -0.817874   -0.742009
16  GBR  -0.319098     0.007397 -0.630576   -0.637926
17  GRC  -4.850642    -0.188532 -0.770973   -0.583541
18  HRV  -3.519963    -0.339114 -0.941435   -0.604371
19  HUN  -3.292692    -0.219500 -0.938382   -0.720463
20  IDN  -0.301701     0.003974 -0.541698   -0.545651
21  IND  -0.337481     0.004423 -0.548190   -0.552589
22  IRL  -4.671054    -0.231085 -0.939180   -0.709735
23  ITA  -4.213013    -0.072377 -0.875046   -0.803250
24  JPN  -0.311974     0.001916 -0.530958   -0.532864
25  KOR  -0.281808     0.001175 -0.549576   -0.550744
26  LTU  -3.129512    -0.376497 -0.951048   -0.576722
27  LUX  -3.709380    -0.161715 -0.784535   -0.623829
28  LVA  -3.282201    -0.416899 -0.955148   -0.540503
29  MEX   0.091202     0.009904 -0.343513   -0.353382
30  MLT  -4.954362    -0.318037 -0.912714   -0.596574
31  NLD  -3.155466    -0.094372 -0.981964   -0.888430
32  NOR  -0.329502     0.014138 -0.627198   -0.641245
33  POL  -3.497199    -0.135564 -0.883532   -0.748983
34  PRT  -5.994726    -0.217849 -0.826759   -0.610240
35  ROU  -4.206099    -0.204935 -0.865523   -0.661944
36  RUS  -0.334838     0.011581 -0.602765   -0.614274
37  SVK  -2.864607    -0.219456 -0.945691   -0.727833
38  SVN  -3.098370    -0.298360 -0.953689   -0.657290
39  SWE  -4.397937    -0.160953 -0.863540   -0.703720
40  TUR  -0.320032     0.011324 -0.609122   -0.620375
41  TWN  -0.301351     0.001338 -0.552624   -0.553955
42  USA -13.942561    -0.093104  0.000000    0.093191

   País    Export%  Renta_Real%   Output%  P_Consumo%
0   AUS  -0.238722     0.003905 -0.513390   -0.517274
1   AUT  -3.080707    -0.127617 -0.895741   -0.769105
2   BEL  -3.102621    -0.105718 -0.887013   -0.782122
3   BGR  -3.552989    -0.318708 -0.900743   -0.583896
4   BRA  -0.150488     0.005012 -0.496541   -0.501528
5   CAN   0.247300     0.021532 -0.190881   -0.212367
6   CHE  -0.395563     0.010677 -0.688738   -0.699340
7   CHN  -0.267996     0.001090 -0.547446   -0.548529
8   CYP  -4.677608    -0.363714 -0.884645   -0.522832
9   CZE  -3.012601    -0.167797 -0.943000   -0.776506
10  DEU  -3.137058    -0.058772 -0.929657   -0.871398
11  DNK  -3.838220    -0.148373 -0.902827   -0.755576
12  ESP  -5.452268    -0.110479 -0.847912   -0.738248
13  EST  -3.203936    -0.435010 -0.971268   -0.538601
14  FIN  -3.900884    -0.206141 -0.861618   -0.656831
15  FRA  -4.129529    -0.076432 -0.817874   -0.742009
16  GBR  -0.319098     0.007397 -0.630576   -0.637926
17  GRC  -4.850642    -0.188532 -0.770973   -0.583541
18  HRV  -3.519963    -0.339114 -0.941435   -0.604371
19  HUN  -3.292692    -0.219500 -0.938382   -0.720463
20  IDN  -0.301701     0.003974 -0.541698   -0.545651
21  IND  -0.337481     0.004423 -0.548190   -0.552589
22  IRL  -4.671054    -0.231085 -0.939180   -0.709735
23  ITA  -4.213013    -0.072377 -0.875046   -0.803250
24  JPN  -0.311974     0.001916 -0.530958   -0.532864
25  KOR  -0.281808     0.001175 -0.549576   -0.550744
26  LTU  -3.129512    -0.376497 -0.951048   -0.576722
27  LUX  -3.709380    -0.161715 -0.784535   -0.623829
28  LVA  -3.282201    -0.416899 -0.955148   -0.540503
29  MEX   0.091202     0.009904 -0.343513   -0.353382
30  MLT  -4.954362    -0.318037 -0.912714   -0.596574
31  NLD  -3.155466    -0.094372 -0.981964   -0.888430
32  NOR  -0.329502     0.014138 -0.627198   -0.641245
33  POL  -3.497199    -0.135564 -0.883532   -0.748983
34  PRT  -5.994726    -0.217849 -0.826759   -0.610240
35  ROU  -4.206099    -0.204935 -0.865523   -0.661944
36  RUS  -0.334838     0.011581 -0.602765   -0.614274
37  SVK  -2.864607    -0.219456 -0.945691   -0.727833
38  SVN  -3.098370    -0.298360 -0.953689   -0.657290
39  SWE  -4.397937    -0.160953 -0.863540   -0.703720
40  TUR  -0.320032     0.011324 -0.609122   -0.620375
41  TWN  -0.301351     0.001338 -0.552624   -0.553955
42  USA -13.942561    -0.093104  0.000000    0.093191

In [103]:
# A counterfactual in which one country is treated **as if** it were another

(it.struc_grav_asif(obj_grav, variables, paises1, paises2, paises3, pais_ref, sigma))

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                  trade   No. Observations:                 1849
Model:                            GLM   Df Residuals:                     1758
Model Family:                 Poisson   Df Model:                           90
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:            -3.0458e+06
Date:                Fri, 03 Apr 2026   Deviance:                   6.0753e+06
Time:                        15:46:33   Pearson chi2:                 6.98e+06
No. Iterations:                    12   Pseudo R-squ. (CS):              1.000
Covariance Type:                  HC3
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
LN_DIST        -0.5666      0.045    -12.527      0.000      -0.655      -0.478
CNTG            0.7063      0.160      4.425      0.000       0.393       1.019
LANG            0.0920      0.134      0.687      0.492      -0.171       0.355
BRDR           -4.1404      0.119    -34.703      0.000      -4.374      -3.907
if_USA_as_     -3.6058      0.182    -19.849      0.000      -3.962      -3.250
ref_GBR_FTA    -3.5117      0.179    -19.574      0.000      -3.863      -3.160
exp_fe_AUS     18.2873      0.356     51.406      0.000      17.590      18.984
exp_fe_AUT     16.6310      0.337     49.304      0.000      15.970      17.292
exp_fe_BEL     16.6575      0.312     53.467      0.000      16.047      17.268
exp_fe_BGR     15.4916      0.351     44.087      0.000      14.803      16.180
exp_fe_BRA     18.3910      0.338     54.416      0.000      17.729      19.053
exp_fe_CAN     18.1393      0.351     51.665      0.000      17.451      18.827
exp_fe_CHE     17.1054      0.300     56.973      0.000      16.517      17.694
exp_fe_CHN     19.6940      0.359     54.877      0.000      18.991      20.397
exp_fe_CYP     14.5409      0.352     41.325      0.000      13.851      15.231
exp_fe_CZE     16.3859      0.310     52.905      0.000      15.779      16.993
exp_fe_DEU     18.1331      0.305     59.436      0.000      17.535      18.731
exp_fe_DNK     16.3712      0.303     54.093      0.000      15.778      16.964
exp_fe_ESP     17.4748      0.333     52.516      0.000      16.823      18.127
exp_fe_EST     14.8939      0.362     41.147      0.000      14.184      15.603
exp_fe_FIN     16.5292      0.331     49.870      0.000      15.880      17.179
exp_fe_FRA     17.7988      0.318     56.020      0.000      17.176      18.422
exp_fe_GBR     18.1123      0.304     59.488      0.000      17.516      18.709
exp_fe_GRC     16.1095      0.336     47.937      0.000      15.451      16.768
exp_fe_HRV     15.2409      0.372     41.006      0.000      14.512      15.969
exp_fe_HUN     16.0724      0.367     43.809      0.000      15.353      16.792
exp_fe_IDN     17.8740      0.332     53.915      0.000      17.224      18.524
exp_fe_IND     18.3172      0.367     49.958      0.000      17.599      19.036
exp_fe_IRL     16.2656      0.424     38.353      0.000      15.434      17.097
exp_fe_ITA     17.7336      0.340     52.124      0.000      17.067      18.400
exp_fe_JPN     18.4512      0.331     55.707      0.000      17.802      19.100
exp_fe_KOR     18.0172      0.379     47.484      0.000      17.273      18.761
exp_fe_LTU     15.1754      0.346     43.802      0.000      14.496      15.854
exp_fe_LUX     15.0258      0.353     42.595      0.000      14.334      15.717
exp_fe_LVA     15.0244      0.404     37.198      0.000      14.233      15.816
exp_fe_MEX     17.8722      0.444     40.276      0.000      17.003      18.742
exp_fe_MLT     14.0040      0.385     36.363      0.000      13.249      14.759
exp_fe_NLD     17.0940      0.413     41.376      0.000      16.284      17.904
exp_fe_NOR     17.1687      0.323     53.110      0.000      16.535      17.802
exp_fe_POL     16.9970      0.322     52.854      0.000      16.367      17.627
exp_fe_PRT     16.1629      0.326     49.548      0.000      15.524      16.802
exp_fe_ROU     16.3406      0.334     48.902      0.000      15.686      16.995
exp_fe_RUS     18.3686      0.349     52.584      0.000      17.684      19.053
exp_fe_SVK     15.8458      0.330     47.991      0.000      15.199      16.493
exp_fe_SVN     15.1534      0.336     45.128      0.000      14.495      15.812
exp_fe_SWE     16.9572      0.326     51.945      0.000      16.317      17.597
exp_fe_TUR     17.4823      0.317     55.097      0.000      16.860      18.104
exp_fe_TWN     17.3441      0.421     41.233      0.000      16.520      18.169
exp_fe_USA     19.3031      0.335     57.685      0.000      18.647      19.959
imp_fe_AUS      0.3427      0.218      1.572      0.116      -0.085       0.770
imp_fe_AUT     -1.2406      0.222     -5.580      0.000      -1.676      -0.805
imp_fe_BEL     -1.2128      0.203     -5.971      0.000      -1.611      -0.815
imp_fe_BGR     -2.1879      0.227     -9.627      0.000      -2.633      -1.742
imp_fe_BRA      0.7060      0.189      3.736      0.000       0.336       1.076
imp_fe_CAN      0.5843      0.218      2.676      0.007       0.156       1.012
imp_fe_CHE     -0.7700      0.203     -3.789      0.000      -1.168      -0.372
imp_fe_CHN      1.5015      0.216      6.960      0.000       1.079       1.924
imp_fe_CYP     -3.0304      0.235    -12.882      0.000      -3.491      -2.569
imp_fe_CZE     -1.5852      0.165     -9.598      0.000      -1.909      -1.262
imp_fe_DNK     -1.4633      0.171     -8.555      0.000      -1.799      -1.128
imp_fe_ESP     -0.2621      0.194     -1.351      0.177      -0.642       0.118
imp_fe_EST     -2.8595      0.254    -11.244      0.000      -3.358      -2.361
imp_fe_FIN     -1.2258      0.192     -6.368      0.000      -1.603      -0.849
imp_fe_FRA      0.1188      0.166      0.715      0.474      -0.207       0.444
imp_fe_GBR      0.1913      0.193      0.993      0.321      -0.186       0.569
imp_fe_GRC     -1.3605      0.203     -6.698      0.000      -1.759      -0.962
imp_fe_HRV     -2.4402      0.255     -9.566      0.000      -2.940      -1.940
imp_fe_HUN     -1.8418      0.250     -7.365      0.000      -2.332      -1.352
imp_fe_IDN     -0.1438      0.190     -0.758      0.449      -0.516       0.228
imp_fe_IND      0.4119      0.249      1.655      0.098      -0.076       0.900
imp_fe_IRL     -1.5564      0.354     -4.399      0.000      -2.250      -0.863
imp_fe_ITA     -0.1736      0.208     -0.835      0.404      -0.581       0.234
imp_fe_JPN      0.5241      0.216      2.422      0.015       0.100       0.948
imp_fe_KOR     -0.4417      0.270     -1.636      0.102      -0.971       0.087
imp_fe_LTU     -2.6009      0.227    -11.475      0.000      -3.045      -2.157
imp_fe_LUX     -2.2647      0.311     -7.276      0.000      -2.875      -1.655
imp_fe_LVA     -2.6805      0.296     -9.061      0.000      -3.260      -2.101
imp_fe_MEX      0.1008      0.362      0.278      0.781      -0.608       0.810
imp_fe_MLT     -3.6604      0.311    -11.788      0.000      -4.269      -3.052
imp_fe_NLD     -1.1072      0.343     -3.224      0.001      -1.780      -0.434
imp_fe_NOR     -0.7833      0.205     -3.818      0.000      -1.185      -0.381
imp_fe_POL     -0.8754      0.170     -5.165      0.000      -1.208      -0.543
imp_fe_PRT     -1.3841      0.206     -6.729      0.000      -1.787      -0.981
imp_fe_ROU     -1.3855      0.200     -6.943      0.000      -1.777      -0.994
imp_fe_RUS      0.5680      0.208      2.735      0.006       0.161       0.975
imp_fe_SVK     -2.0876      0.219     -9.553      0.000      -2.516      -1.659
imp_fe_SVN     -2.6545      0.220    -12.058      0.000      -3.086      -2.223
imp_fe_SWE     -0.8139      0.178     -4.574      0.000      -1.163      -0.465
imp_fe_TUR     -0.2042      0.187     -1.091      0.275      -0.571       0.163
imp_fe_TWN     -1.1730      0.337     -3.484      0.000      -1.833      -0.513
imp_fe_USA      1.8878      0.189      9.967      0.000       1.517       2.259
===============================================================================
trade        1.302876e+08
trade_BLN    1.302876e+08
dtype: float64
If['USA'] behaves as ['GBR'] in relation to ['AUT', 'BEL', 'BGR', 'HRV', 'CYP', 'CZE', 'DNK', 'EST', 'FIN', 'FRA', 'DEU', 'GRC', 'IRL', 'HUN', 'ITA', 'LVA', 'LTU', 'LUX', 'MLT', 'POL', 'NLD', 'PRT', 'ROU', 'SVK', 'SVN', 'ESP', 'SWE']
5.704350769519806e-09
0.01914798776851967 2.7026544557884336e-08 0.0
   País   Export%  Renta_Real%   Output%  P_Consumo%
0   AUS -0.560146    -0.012048  0.202846    0.214920
1   AUT  0.016850     1.521657  1.064731   -0.450078
2   BEL -0.011964     1.532721  1.068136   -0.457572
3   BGR -0.320728     1.414341  1.026976   -0.381963
4   BRA -0.906537    -0.013730  0.216169    0.229931
5   CAN -0.394546    -0.023055  0.092397    0.115478
6   CHE -1.927305    -0.072634  0.261762    0.334639
7   CHN -0.489089    -0.004820  0.206171    0.211002
8   CYP -0.597902     1.403720  1.037829   -0.360826
9   CZE  0.076888     1.511412  1.057980   -0.446681
10  DEU -0.204452     1.558068  1.078460   -0.472250
11  DNK -0.196858     1.517359  1.064825   -0.445770
12  ESP -0.463583     1.543830  1.099237   -0.437833
13  EST -0.232181     1.347479  0.989714   -0.353008
14  FIN -0.668081     1.468223  1.045278   -0.416825
15  FRA -0.446746     1.543069  1.080814   -0.455231
16  GBR -2.246151    -0.043431  0.351741    0.395344
17  GRC -0.813672     1.479301  1.073861   -0.399530
18  HRV -0.026904     1.429824  1.035138   -0.389122
19  HUN -0.059021     1.488294  1.052896   -0.429014
20  IDN -0.549514    -0.015316  0.207427    0.222777
21  IND -0.591159    -0.015597  0.214289    0.229921
22  IRL -0.786116     1.473771  1.041041   -0.426445
23  ITA -0.502342     1.551266  1.084543   -0.459594
24  JPN -0.523755    -0.006018  0.209763    0.215794
25  KOR -0.299580    -0.007686  0.194150    0.201852
26  LTU -0.255142     1.370174  0.995360   -0.369748
27  LUX  0.065562     1.487585  1.062566   -0.418789
28  LVA -0.277845     1.351116  0.992611   -0.353726
29  MEX -0.549378    -0.016467  0.146844    0.163338
30  MLT -0.377357     1.452125  1.058387   -0.388102
31  NLD -0.222963     1.544089  1.063352   -0.473427
32  NOR -1.181664    -0.071357  0.226215    0.297785
33  POL -0.367594     1.512076  1.055043   -0.450226
34  PRT -0.384638     1.507542  1.095982   -0.405447
35  ROU -0.500456     1.484498  1.059473   -0.418808
36  RUS -1.165089    -0.047869  0.235405    0.283409
37  SVK  0.137908     1.488854  1.051483   -0.430954
38  SVN  0.115236     1.451254  1.039558   -0.405807
39  SWE -0.588316     1.507445  1.068285   -0.432638
40  TUR -1.393621    -0.047075  0.254173    0.301390
41  TWN -0.232043    -0.010620  0.193167    0.203808
42  USA  0.349868     0.002626  0.000000   -0.002626

   País   Export%  Renta_Real%   Output%  P_Consumo%
0   AUS -0.560146    -0.012048  0.202846    0.214920
1   AUT  0.016850     1.521657  1.064731   -0.450078
2   BEL -0.011964     1.532721  1.068136   -0.457572
3   BGR -0.320728     1.414341  1.026976   -0.381963
4   BRA -0.906537    -0.013730  0.216169    0.229931
5   CAN -0.394546    -0.023055  0.092397    0.115478
6   CHE -1.927305    -0.072634  0.261762    0.334639
7   CHN -0.489089    -0.004820  0.206171    0.211002
8   CYP -0.597902     1.403720  1.037829   -0.360826
9   CZE  0.076888     1.511412  1.057980   -0.446681
10  DEU -0.204452     1.558068  1.078460   -0.472250
11  DNK -0.196858     1.517359  1.064825   -0.445770
12  ESP -0.463583     1.543830  1.099237   -0.437833
13  EST -0.232181     1.347479  0.989714   -0.353008
14  FIN -0.668081     1.468223  1.045278   -0.416825
15  FRA -0.446746     1.543069  1.080814   -0.455231
16  GBR -2.246151    -0.043431  0.351741    0.395344
17  GRC -0.813672     1.479301  1.073861   -0.399530
18  HRV -0.026904     1.429824  1.035138   -0.389122
19  HUN -0.059021     1.488294  1.052896   -0.429014
20  IDN -0.549514    -0.015316  0.207427    0.222777
21  IND -0.591159    -0.015597  0.214289    0.229921
22  IRL -0.786116     1.473771  1.041041   -0.426445
23  ITA -0.502342     1.551266  1.084543   -0.459594
24  JPN -0.523755    -0.006018  0.209763    0.215794
25  KOR -0.299580    -0.007686  0.194150    0.201852
26  LTU -0.255142     1.370174  0.995360   -0.369748
27  LUX  0.065562     1.487585  1.062566   -0.418789
28  LVA -0.277845     1.351116  0.992611   -0.353726
29  MEX -0.549378    -0.016467  0.146844    0.163338
30  MLT -0.377357     1.452125  1.058387   -0.388102
31  NLD -0.222963     1.544089  1.063352   -0.473427
32  NOR -1.181664    -0.071357  0.226215    0.297785
33  POL -0.367594     1.512076  1.055043   -0.450226
34  PRT -0.384638     1.507542  1.095982   -0.405447
35  ROU -0.500456     1.484498  1.059473   -0.418808
36  RUS -1.165089    -0.047869  0.235405    0.283409
37  SVK  0.137908     1.488854  1.051483   -0.430954
38  SVN  0.115236     1.451254  1.039558   -0.405807
39  SWE -0.588316     1.507445  1.068285   -0.432638
40  TUR -1.393621    -0.047075  0.254173    0.301390
41  TWN -0.232043    -0.010620  0.193167    0.203808
42  USA  0.349868     0.002626  0.000000   -0.002626

In [104]:
# A counterfactual one country in/out a set of countries (eg. FTA)

(it.struc_grav_inout(obj_grav, variables, paises1, paises2, pais_ref, sigma))

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                  trade   No. Observations:                 1849
Model:                            GLM   Df Residuals:                     1759
Model Family:                 Poisson   Df Model:                           89
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:            -3.0047e+06
Date:                Fri, 03 Apr 2026   Deviance:                   5.9932e+06
Time:                        15:46:38   Pearson chi2:                 7.12e+06
No. Iterations:                    10   Pseudo R-squ. (CS):              1.000
Covariance Type:                  HC3
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
LN_DIST         -0.5854      0.040    -14.568      0.000      -0.664      -0.507
CNTG             0.5540      0.161      3.448      0.001       0.239       0.869
LANG             0.1733      0.132      1.317      0.188      -0.085       0.431
BRDR            -4.2100      0.111    -37.965      0.000      -4.427      -3.993
RTA27_in_out     0.4458      0.087      5.116      0.000       0.275       0.617
exp_fe_AUS      18.6507      0.325     57.411      0.000      18.014      19.287
exp_fe_AUT      17.2422      0.259     66.528      0.000      16.734      17.750
exp_fe_BEL      17.2721      0.243     71.105      0.000      16.796      17.748
exp_fe_BGR      16.0948      0.315     51.159      0.000      15.478      16.711
exp_fe_BRA      18.7528      0.292     64.115      0.000      18.180      19.326
exp_fe_CAN      18.5018      0.302     61.204      0.000      17.909      19.094
exp_fe_CHE      17.4509      0.260     67.142      0.000      16.941      17.960
exp_fe_CHN      20.0744      0.320     62.759      0.000      19.447      20.701
exp_fe_CYP      15.1418      0.315     48.015      0.000      14.524      15.760
exp_fe_CZE      16.9857      0.238     71.266      0.000      16.519      17.453
exp_fe_DEU      18.7516      0.231     81.285      0.000      18.299      19.204
exp_fe_DNK      16.9863      0.246     69.085      0.000      16.504      17.468
exp_fe_ESP      18.1206      0.261     69.372      0.000      17.609      18.633
exp_fe_EST      15.4713      0.331     46.772      0.000      14.823      16.120
exp_fe_FIN      17.1507      0.277     62.026      0.000      16.609      17.693
exp_fe_FRA      18.4518      0.251     73.530      0.000      17.960      18.944
exp_fe_GBR      18.2828      0.272     67.336      0.000      17.751      18.815
exp_fe_GRC      16.7484      0.287     58.371      0.000      16.186      17.311
exp_fe_HRV      15.8306      0.352     44.999      0.000      15.141      16.520
exp_fe_HUN      16.6711      0.288     57.940      0.000      16.107      17.235
exp_fe_IDN      18.2396      0.290     62.997      0.000      17.672      18.807
exp_fe_IND      18.6726      0.312     59.785      0.000      18.060      19.285
exp_fe_IRL      16.9068      0.366     46.151      0.000      16.189      17.625
exp_fe_ITA      18.3661      0.264     69.442      0.000      17.848      18.885
exp_fe_JPN      18.8048      0.304     61.790      0.000      18.208      19.401
exp_fe_KOR      18.3845      0.375     49.006      0.000      17.649      19.120
exp_fe_LTU      15.7617      0.313     50.430      0.000      15.149      16.374
exp_fe_LUX      15.6504      0.289     54.142      0.000      15.084      16.217
exp_fe_LVA      15.6096      0.388     40.220      0.000      14.849      16.370
exp_fe_MEX      18.2431      0.490     37.238      0.000      17.283      19.203
exp_fe_MLT      14.5917      0.323     45.116      0.000      13.958      15.226
exp_fe_NLD      17.6971      0.334     53.058      0.000      17.043      18.351
exp_fe_NOR      17.5273      0.278     63.105      0.000      16.983      18.072
exp_fe_POL      17.6182      0.252     69.999      0.000      17.125      18.111
exp_fe_PRT      16.8006      0.262     64.133      0.000      16.287      17.314
exp_fe_ROU      16.9620      0.275     61.663      0.000      16.423      17.501
exp_fe_RUS      18.7383      0.300     62.472      0.000      18.150      19.326
exp_fe_SVK      16.4336      0.269     61.076      0.000      15.906      16.961
exp_fe_SVN      15.7382      0.294     53.615      0.000      15.163      16.313
exp_fe_SWE      17.5875      0.261     67.481      0.000      17.077      18.098
exp_fe_TUR      17.8409      0.272     65.615      0.000      17.308      18.374
exp_fe_TWN      17.7045      0.408     43.442      0.000      16.906      18.503
exp_fe_USA      19.6451      0.305     64.415      0.000      19.047      20.243
imp_fe_AUS       0.1133      0.212      0.535      0.593      -0.302       0.529
imp_fe_AUT      -1.2839      0.170     -7.532      0.000      -1.618      -0.950
imp_fe_BEL      -1.2635      0.163     -7.739      0.000      -1.584      -0.944
imp_fe_BGR      -2.2552      0.228     -9.874      0.000      -2.703      -1.808
imp_fe_BRA       0.4787      0.168      2.857      0.004       0.150       0.807
imp_fe_CAN       0.3734      0.188      1.985      0.047       0.005       0.742
imp_fe_CHE      -1.0381      0.178     -5.841      0.000      -1.386      -0.690
imp_fe_CHN       1.2563      0.199      6.313      0.000       0.866       1.646
imp_fe_CYP      -3.1042      0.226    -13.743      0.000      -3.547      -2.662
imp_fe_CZE      -1.6271      0.132    -12.350      0.000      -1.885      -1.369
imp_fe_DNK      -1.5078      0.158     -9.556      0.000      -1.817      -1.199
imp_fe_ESP      -0.2875      0.149     -1.925      0.054      -0.580       0.005
imp_fe_EST      -2.9412      0.262    -11.239      0.000      -3.454      -2.428
imp_fe_FIN      -1.2639      0.176     -7.184      0.000      -1.609      -0.919
imp_fe_FRA       0.0858      0.134      0.640      0.522      -0.177       0.349
imp_fe_GBR       0.1328      0.182      0.729      0.466      -0.224       0.490
imp_fe_GRC      -1.4159      0.184     -7.685      0.000      -1.777      -1.055
imp_fe_HRV      -2.5281      0.274     -9.232      0.000      -3.065      -1.991
imp_fe_HUN      -1.8921      0.197     -9.617      0.000      -2.278      -1.507
imp_fe_IDN      -0.3854      0.169     -2.284      0.022      -0.716      -0.055
imp_fe_IND       0.1876      0.207      0.904      0.366      -0.219       0.594
imp_fe_IRL      -1.6082      0.344     -4.669      0.000      -2.283      -0.933
imp_fe_ITA      -0.1887      0.160     -1.181      0.238      -0.502       0.124
imp_fe_JPN       0.2757      0.214      1.287      0.198      -0.144       0.696
imp_fe_KOR      -0.7140      0.281     -2.537      0.011      -1.266      -0.162
imp_fe_LTU      -2.6726      0.234    -11.406      0.000      -3.132      -2.213
imp_fe_LUX      -2.3781      0.293     -8.111      0.000      -2.953      -1.803
imp_fe_LVA      -2.7602      0.313     -8.808      0.000      -3.374      -2.146
imp_fe_MEX      -0.1379      0.440     -0.313      0.754      -1.000       0.725
imp_fe_MLT      -3.7419      0.270    -13.872      0.000      -4.271      -3.213
imp_fe_NLD      -1.1226      0.277     -4.056      0.000      -1.665      -0.580
imp_fe_NOR      -1.0332      0.175     -5.917      0.000      -1.375      -0.691
imp_fe_POL      -0.9026      0.134     -6.718      0.000      -1.166      -0.639
imp_fe_PRT      -1.4336      0.168     -8.545      0.000      -1.762      -1.105
imp_fe_ROU      -1.4309      0.177     -8.098      0.000      -1.777      -1.085
imp_fe_RUS       0.3447      0.172      1.999      0.046       0.007       0.683
imp_fe_SVK      -2.1473      0.197    -10.884      0.000      -2.534      -1.761
imp_fe_SVN      -2.7322      0.221    -12.387      0.000      -3.165      -2.300
imp_fe_SWE      -0.8475      0.147     -5.767      0.000      -1.136      -0.560
imp_fe_TUR      -0.4528      0.157     -2.882      0.004      -0.761      -0.145
imp_fe_TWN      -1.4482      0.338     -4.287      0.000      -2.110      -0.786
imp_fe_USA       1.6882      0.200      8.447      0.000       1.296       2.080
================================================================================
trade        1.302876e+08
trade_BLN    1.302876e+08
dtype: float64
['AUT', 'BEL', 'BGR', 'HRV', 'CYP', 'CZE', 'DNK', 'EST', 'FIN', 'FRA', 'DEU', 'GRC', 'IRL', 'HUN', 'ITA', 'LVA', 'LTU', 'LUX', 'MLT', 'POL', 'NLD', 'PRT', 'ROU', 'SVK', 'SVN', 'ESP', 'SWE']---IN---['USA']
5.820766091346741e-10
0.01407005378860049 1.9274011719971895e-08 0.0
   País    Export%  Renta_Real%   Output%  P_Consumo%
0   AUS   0.175588    -0.003398  0.423839    0.427251
1   AUT   2.608932     0.129171  0.771606    0.641606
2   BEL   2.578660     0.107276  0.759788    0.651813
3   BGR   3.057363     0.322529  0.802236    0.478165
4   BRA   0.114301    -0.004080  0.417847    0.421944
5   CAN  -0.230327    -0.017364  0.167352    0.184748
6   CHE   0.306963    -0.008857  0.577179    0.586088
7   CHN   0.207723    -0.000888  0.458663    0.459555
8   CYP   3.989954     0.374307  0.795795    0.419917
9   CZE   2.574745     0.169869  0.809480    0.638527
10  DEU   2.829773     0.059618  0.784838    0.724788
11  DNK   3.303630     0.151677  0.778905    0.626278
12  ESP   4.866398     0.112834  0.731213    0.617681
13  EST   2.729285     0.435292  0.867786    0.430620
14  FIN   3.498530     0.209281  0.759441    0.549011
15  FRA   3.647807     0.077883  0.705429    0.627057
16  GBR   0.226406    -0.006297  0.522273    0.528604
17  GRC   4.300739     0.194240  0.688936    0.493737
18  HRV   2.864035     0.339806  0.833061    0.491585
19  HUN   2.798766     0.221731  0.813776    0.590735
20  IDN   0.241363    -0.003271  0.454341    0.457627
21  IND   0.250190    -0.003846  0.454220    0.458083
22  IRL   4.541414     0.261634  0.833607    0.570480
23  ITA   3.793353     0.073855  0.747463    0.673111
24  JPN   0.250800    -0.001577  0.445256    0.446840
25  KOR   0.224138    -0.000975  0.461131    0.462111
26  LTU   2.704423     0.378632  0.847160    0.466761
27  LUX   2.910598     0.167357  0.704438    0.536184
28  LVA   2.808848     0.418298  0.854706    0.434590
29  MEX  -0.067312    -0.007461  0.305399    0.312884
30  MLT   4.459564     0.365360  0.830500    0.463447
31  NLD   2.818214     0.096576  0.825064    0.727785
32  NOR   0.249836    -0.011481  0.525415    0.536958
33  POL   3.112150     0.137882  0.765774    0.627028
34  PRT   5.196920     0.223831  0.731734    0.506769
35  ROU   3.656348     0.208832  0.760177    0.550197
36  RUS   0.254328    -0.009343  0.505308    0.514699
37  SVK   2.408783     0.220547  0.818427    0.596564
38  SVN   2.563097     0.299768  0.835134    0.533766
39  SWE   3.874910     0.163500  0.753104    0.588642
40  TUR   0.246356    -0.009334  0.511585    0.520967
41  TWN   0.248466    -0.001119  0.463546    0.464670
42  USA  16.410807     0.096006  0.000000   -0.095914

   País    Export%  Renta_Real%   Output%  P_Consumo%
0   AUS   0.175588    -0.003398  0.423839    0.427251
1   AUT   2.608932     0.129171  0.771606    0.641606
2   BEL   2.578660     0.107276  0.759788    0.651813
3   BGR   3.057363     0.322529  0.802236    0.478165
4   BRA   0.114301    -0.004080  0.417847    0.421944
5   CAN  -0.230327    -0.017364  0.167352    0.184748
6   CHE   0.306963    -0.008857  0.577179    0.586088
7   CHN   0.207723    -0.000888  0.458663    0.459555
8   CYP   3.989954     0.374307  0.795795    0.419917
9   CZE   2.574745     0.169869  0.809480    0.638527
10  DEU   2.829773     0.059618  0.784838    0.724788
11  DNK   3.303630     0.151677  0.778905    0.626278
12  ESP   4.866398     0.112834  0.731213    0.617681
13  EST   2.729285     0.435292  0.867786    0.430620
14  FIN   3.498530     0.209281  0.759441    0.549011
15  FRA   3.647807     0.077883  0.705429    0.627057
16  GBR   0.226406    -0.006297  0.522273    0.528604
17  GRC   4.300739     0.194240  0.688936    0.493737
18  HRV   2.864035     0.339806  0.833061    0.491585
19  HUN   2.798766     0.221731  0.813776    0.590735
20  IDN   0.241363    -0.003271  0.454341    0.457627
21  IND   0.250190    -0.003846  0.454220    0.458083
22  IRL   4.541414     0.261634  0.833607    0.570480
23  ITA   3.793353     0.073855  0.747463    0.673111
24  JPN   0.250800    -0.001577  0.445256    0.446840
25  KOR   0.224138    -0.000975  0.461131    0.462111
26  LTU   2.704423     0.378632  0.847160    0.466761
27  LUX   2.910598     0.167357  0.704438    0.536184
28  LVA   2.808848     0.418298  0.854706    0.434590
29  MEX  -0.067312    -0.007461  0.305399    0.312884
30  MLT   4.459564     0.365360  0.830500    0.463447
31  NLD   2.818214     0.096576  0.825064    0.727785
32  NOR   0.249836    -0.011481  0.525415    0.536958
33  POL   3.112150     0.137882  0.765774    0.627028
34  PRT   5.196920     0.223831  0.731734    0.506769
35  ROU   3.656348     0.208832  0.760177    0.550197
36  RUS   0.254328    -0.009343  0.505308    0.514699
37  SVK   2.408783     0.220547  0.818427    0.596564
38  SVN   2.563097     0.299768  0.835134    0.533766
39  SWE   3.874910     0.163500  0.753104    0.588642
40  TUR   0.246356    -0.009334  0.511585    0.520967
41  TWN   0.248466    -0.001119  0.463546    0.464670
42  USA  16.410807     0.096006  0.000000   -0.095914